print("my name is Shelby")
print("I was born in December")
print('My name is cooper')
print("My name is Cami")
print("I was born in December too, Shelby")
print('my favorite food is ice cream')
print('I was born in NJ')
print('my favorite color is blue')
print("my favorite food is ice creams")
print("my favorite fruit is strawberries")
print("I was born in California")
print("My sisters are twins")
print("My favorite color is purple")
print("My dogs name Roxy")
print('My favorite food is anyting gluten free :(')
print('this is repetitive')
