print("my name is Shelby")
print("I was born in December")
print('My name is cooper')
print("My name is Cami")
print("I was born in December too, Shelby")
print('My favorite food is anyting gluten free :(')
