print("my name is Shelby")
print("I was born in December")
print('My name is cooper')
print("My name is Cami")
print("I was born in December too, Shelby")
print("my favorite food is ice creams")
print("my favorite fruit is strawberries")
